language: python
python:
  - "3.4"
  - "2.7"
  - "3.5"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script:
  - "py.test /sqlalchemy_jsonapi/tests/"
  - "nosetests /sqlalchemy_jsonapi/unittests/"